# #######################################################################################
# HYPRLAND CONFIG.
# #######################################################################################

# This configuration is split into multiple files

# --- Environment variables ---
source = hyprland/env.conf

# --- Other vars ---
source = hyprland/variables.conf

# --- Defaults ---
source = hyprland/execs.conf
source = hyprland/general.conf
source = hyprland/rules.conf
source = noctalia/noctalia-colors.conf
source = hyprland/keybinds.conf

source = /home/alex/.config/hypr/noctalia/noctalia-colors.conf

