# #######################################################################################
# HYPRLAND CONFIG.
# #######################################################################################

# This configuration is split into multiple files

# --- Environment variables ---
# source = hyprland/env.conf

source = hyprland/monitors.conf
source = hyprland/programs.conf
source = hyprland/variables.conf
source = hyprland/permissions.conf
source = hyprland/layouts.conf
source = hyprland/input.conf
source = hyprland/keybinds.conf
