###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$lockscreen = qs -c noctalia-shell ipc call lockScreen lock

$menu = qs -c noctalia-shell ipc call launcher toggle
